var KEYWORD = {
	ADD_KEYWORD: 'ADD_KEYWORD',
	DELETE_KEYWORD: 'DELETE_KEYWORD',
	SORT_KEYWORD: 'SORT_KEYWORD',
	EMPTY_KEYWORDS: 'EMPTY_KEYWORDS'
};

var SUBWAY = {
	TOGGLE_SUBWAY: 'TOGGLE_SUBWAY',
	DESELECT_SUBWAYS: 'DESELECT_SUBWAYS'
};

var SOURCE = {
	TOGGLE_SOURCE: 'TOGGLE_SOURCE'
};

var TIME = {
	CHOOSE_TIME: 'CHOOSE_TIME'
};

var PAGINATION = {
	NEXT_PAGE: 'NEXT_PAGE',
	PREV_PAGE: 'PREV_PAGE',
	FIRST_PAGE: 'FIRST_PAGE',
	LAST_PAGE: 'LAST_PAGE',
	TURN_TO_PAGE: 'TURN_TO_PAGE'
};

var DATA = {
	REQUEST_DATA: 'REQUEST_DATA',
	RECEIVE_DATA: 'RECEIVE_DATA'
};

var APP_STATE = {
	CHANGE_TO: 'CHANGE_TO'
};