var KEYWORD = {
	ADD_KEYWORD: 'ADD_KEYWORD',
	DELETE_KEYWORD: 'DELETE_KEYWORD',
	SORT_KEYWORD: 'SORT_KEYWORD',
	EMPTY_KEYWORDS: 'EMPTY_KEYWORDS'
};

var SUBWAY = {
	ADD_SUBWAY: 'ADD_SUBWAY',
	REMOVE_SUBWAY: 'REMOVE_SUBWAY'
};

var SOURCE = {
	TOGGLE_SOURCE: 'TOGGLE_SOURCE'
};

var TIMERANGE = {
	CHOOSE_RANGE: 'CHOOSE_RANGE'
};

var PAGE = {
	NEXT_PAGE: 'NEXT_PAGE',
	PREV_PAGE: 'PREV_PAGE',
	FIRST_PAGE: 'FIRST_PAGE',
	LAST_PAGE: 'LAST_PAGE',
	TURN_TO_PAGE: 'TURN_TO_PAGE'
};